CREATE TABLE `category` (
  `id` smallint(5) NOT NULL AUTO_INCREMENT COMMENT '分类ID',
  `parentid` smallint(5) unsigned NOT NULL DEFAULT '0' COMMENT '父ID',
  `arr_parent_id` varchar(255) NOT NULL COMMENT '所有父id',
  `has_child` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否存在子栏目，1存在',
  `catname` varchar(30) NOT NULL COMMENT '分类名称',
  `listorder` mediumint(5) NOT NULL DEFAULT '0' COMMENT '排序',
	`type` tinyint(1) NOT NULL COMMENT '栏目类型，1=最终列表栏目 2=频道封面 3=外部链接',
	`urlpath` varchar(255) NOT NULL COMMENT 'URL路径，或者外部链接',
	`template_index` varchar(255) NOT NULL COMMENT '频道封面页模板',
	`template_list` varchar(255) NOT NULL COMMENT '列表页模板',
	`template_article` varchar(255) NOT NULL COMMENT '文章页模板',
	`modelid` smallint(5) NOT NULL COMMENT '栏目模型，见model表',
	`image` varchar(100) NOT NULL DEFAULT '' COMMENT '栏目图片',
	`meta_description` char(255) NOT NULL DEFAULT '' COMMENT '栏目description',
  `meta_keywords` varchar(125) NOT NULL DEFAULT '' COMMENT '栏目keywords',
  `meta_title` varchar(125) NOT NULL DEFAULT '' COMMENT '栏目title',
	`setting` text NOT NULL COMMENT '其他设置',
  `created_at` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '创建时间',
  `updated_at` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `arr_parent_id` (`arr_parent_id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COMMENT='分类表';